Checks fixed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,6 +1,7 @@
 name: Generate release (Pypi, tag, & GitHub Release)
 on:
-  workflow_dispatch:
+  push:
+    branches: [ master, main ]
 
 jobs:
   deploy:
@@ -8,32 +9,36 @@ jobs:
     
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v6
+      uses: actions/checkout@main
+    
+    - name: Set up MPI
+      uses: mpi4py/setup-mpi@master
     
     - name: Set up Python
-      uses: actions/setup-python@v6
+      uses: actions/setup-python@main
       with:
         python-version: '3.10'
     
     - name: Install dependencies
       run: |
-        pip install setuptools wheel twine build
+        pip install setuptools wheel twine
+        pip install -r requirements.txt
     
     - name: Get tag name
       id: variables
-      working-directory: ${{ github.workspace }}/${{ vars.FOLDER_WITH_VERSION }}
+      env:
+        FOLDER_WITH_VERSION: ${{ vars.FOLDER_WITH_VERSION }}
       run: |
-        VERSION=$(python -c "from version import __version__; print(__version__)")
-        echo "TAG_NAME=$VERSION" >> $GITHUB_OUTPUT
-        echo "RELEASE_NAME=v$VERSION" >> $GITHUB_OUTPUT
-        echo "Project version: $VERSION"
+        VERSION=$(python -c "import $FOLDER_WITH_VERSION; print('VERSION', 'v'+$FOLDER_WITH_VERSION.__version__)" | grep VERSION | sed "s/VERSION //g") || (echo "Could not import version, check that variables are correctly set!" && exit 1)
+        echo "TAG_NAME=${VERSION#v}" >> $GITHUB_OUTPUT
+        echo "TAG NAME (must not contain version prefix): ${VERSION#v}"
     
     - name: Build and publish
       env:
-        TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
+        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
       run: |
-        python -m build --no-isolation
+        python setup.py sdist
         twine upload dist/* -c "${{ secrets.PYPI_COMMENT }}"
     
     - name: Generate tag
@@ -44,7 +49,7 @@ jobs:
         custom_tag: ${{ steps.variables.outputs.TAG_NAME }}
     
     - name: Create a GitHub release
-      uses: ncipollo/release-action@v1
+      uses: ncipollo/release-action@main
       with:
         tag: ${{ steps.tag_version.outputs.new_tag }}
-        name: ${{ steps.variables.outputs.RELEASE_NAME }}
+        name: ${{ steps.variables.outputs.TAG_NAME }}
